/**
 * Generates codebase-index.md — a compact symbol index for Claude Code.
 * Cheaper than scanning the full tree: read this file first in each session.
 *
 * Usage: pnpm gen:index
 * Auto-run: configured as a Claude Code Stop hook in .claude/settings.json
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs'
import { join, relative } from 'path'

const ROOT = process.cwd()
const OUT = join(ROOT, 'codebase-index.md')

function read(path: string): string {
  try { return readFileSync(path, 'utf-8') } catch { return '' }
}

function listFiles(dir: string, ext: string): string[] {
  try {
    return readdirSync(dir)
      .filter(f => f.endsWith(ext))
      .map(f => join(dir, f))
  } catch { return [] }
}

function extractExports(content: string): string[] {
  const matches = content.match(/export (?:async )?function (\w+)|export const (\w+)|export class (\w+)/g) ?? []
  return matches.map(m => m.replace(/export (?:async )?(?:function|const|class) /, '').trim())
}

function extractApiMethods(content: string, filePath: string): string {
  const methods: string[] = []
  if (/export const GET/.test(content)) methods.push('GET')
  if (/export const POST/.test(content)) methods.push('POST')
  if (/export const PUT/.test(content)) methods.push('PUT')
  if (/export const DELETE/.test(content)) methods.push('DELETE')
  if (/export const PATCH/.test(content)) methods.push('PATCH')
  const needsAuth = /if \(!currentUser\)/.test(content)
  const route = relative(join(ROOT, 'src/pages'), filePath).replace(/\.ts$/, '').replace(/\[/g, '[').replace(/\]/g, ']')
  return `- \`/${route}\` ${methods.join('/')}${needsAuth ? ' 🔒' : ''}`
}

function extractRepoMethods(content: string): string[] {
  return (content.match(/async (\w+)\(/g) ?? []).map(m => m.replace('async ', '').replace('(', ''))
}

// ── Pages ────────────────────────────────────────────────────────────────────
function listPages(dir: string, prefix = ''): string[] {
  const lines: string[] = []
  try {
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry)
      const stat = statSync(full)
      if (stat.isDirectory()) {
        lines.push(...listPages(full, prefix + '/' + entry))
      } else if (entry.endsWith('.astro') || entry.endsWith('.ts')) {
        const name = entry.replace(/\.(astro|ts)$/, '')
        lines.push(`- \`${prefix}/${name}\``)
      }
    }
  } catch { /* skip */ }
  return lines
}

// ── Build ─────────────────────────────────────────────────────────────────────
const sections: string[] = []

sections.push(`# Codebase Index — Resonance
> Auto-generated by \`pnpm gen:index\`. Do not edit manually.
> Last updated: ${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC
`)

// Repositories
sections.push('## Repositories (`src/repositories/`)\n')
for (const file of listFiles(join(ROOT, 'src/repositories'), '.ts')) {
  const name = file.split('/').pop()!
  const content = read(file)
  const methods = extractRepoMethods(content)
  sections.push(`### ${name.replace('.ts', '')}\n\`${methods.join('`, `')}\`\n`)
}

// API routes
sections.push('## API Routes (`src/pages/api/`) — 🔒 = auth required\n')
function walkApiRoutes(dir: string): string[] {
  const lines: string[] = []
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      lines.push(...walkApiRoutes(full))
    } else if (entry.endsWith('.ts') && entry !== 'index.ts') {
      const content = read(full)
      if (/export const (GET|POST|PUT|DELETE|PATCH)/.test(content)) {
        lines.push(extractApiMethods(content, full))
      }
    }
  }
  return lines
}
try {
  sections.push(walkApiRoutes(join(ROOT, 'src/pages/api')).join('\n') + '\n')
} catch { /* skip */ }

// lib/
sections.push('## Utilities (`src/lib/`)\n')
for (const file of listFiles(join(ROOT, 'src/lib'), '.ts')) {
  const name = file.split('/').pop()!
  const content = read(file)
  const exports = extractExports(content)
  if (exports.length > 0) {
    sections.push(`**${name}**: \`${exports.join('`, `')}\``)
  }
}
sections.push('')

// Components summary
sections.push('## Components (`src/components/`)\n')
sections.push('### ui/\n' + listFiles(join(ROOT, 'src/components/ui'), '.astro').map(f => `- \`${f.split('/').pop()}\``).join('\n'))
sections.push('')
sections.push('### explorer/\n' + listFiles(join(ROOT, 'src/components/explorer'), '.astro').map(f => `- \`${f.split('/').pop()}\``).join('\n'))
sections.push('')

// Pages
sections.push('## Pages (`src/pages/`)\n')
sections.push(listPages(join(ROOT, 'src/pages'), '').filter(l => !l.includes('/api/')).join('\n'))
sections.push('')

// i18n
sections.push('## i18n (`src/i18n/`)\n')
sections.push(listFiles(join(ROOT, 'src/i18n'), '.ts').map(f => `- \`${f.split('/').pop()}\``).join('\n'))
sections.push('')

writeFileSync(OUT, sections.join('\n'), 'utf-8')
console.log(`✓ codebase-index.md updated (${new Date().toLocaleTimeString()})`)
